<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class RtpController extends Controller
{


    public function index()
    {
        $jsonString = file_get_contents(database_path('json/data_rtp.json'));
        $data = json_decode($jsonString, true);

        $jsonProvider = file_get_contents(database_path('json/provider_rtp.json'));
        $provider = json_decode($jsonProvider, true);


        $filteredData = [];
        $dataPerProvider = [];

        foreach ($data as $item) {
            if (!isset($dataPerProvider[$item['provider']])) {
                $dataPerProvider[$item['provider']] = 0;
            }

            if ($dataPerProvider[$item['provider']] < 30) {
                $filteredData[] = $item;
                $dataPerProvider[$item['provider']]++;
            }
        }


        return view('rtpslot_page', ['data' => $filteredData,  'provider' => $provider]);
    }

    public function providerRtp($provider) {
        $jsonString = file_get_contents(database_path('json/data_rtp.json'));
        $data = json_decode($jsonString, true);

        $filterGames = array_filter($data, function($data) use ($provider){
            return $data['provider'] == $provider ;
        });

        return view('rtpslot_provider', ['games' => $filterGames,  "provider" => $provider ]);

    }

    public function edit()
    {
        $data = json_decode(File::get(database_path('json/data_rtp.json')), true);
        return view('edit', ['data' => $data]);
    }

    public function update(Request $request)
    {
        $data = json_decode(File::get(database_path('json/data_rtp.json')), true);

        foreach ($data as &$item) {

            $item['pola'] = $this->generateRandomString();
        }


        $result = File::put(database_path('json/data_rtp.json'), json_encode($data, JSON_PRETTY_PRINT));

        return response()->json(['success' => true, 'result' => $result]);
    }




    private function generateRandomString()
    {

        $variables = [
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">100 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1-19">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2-19">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3-19">20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span>',
            '<span id="prov1-pola1-18">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2-18">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3-18">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1-26">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2-26">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3-26">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1-16">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2-16">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3-16">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1-10">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2-10">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3-10">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1-8">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2-8">70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola3-8">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1-6">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola2-6">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3-6">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1-2">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2-2">30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span><br><span id="prov1-pola3-2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1-24">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2-24">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3-24">50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> Auto</span>',
            '<span id="prov1-pola1-22">10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> Auto</span><br><span id="prov1-pola2-22">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3-22">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
        ];


        $randomVariable = $variables[array_rand($variables)];

        return $randomVariable;

    }
}