<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class RtpController extends Controller
{


    public function index()
    {
        $jsonString = file_get_contents(database_path('json/data_rtp.json'));
        $data = json_decode($jsonString, true);

        $jsonProvider = file_get_contents(database_path('json/provider_rtp.json'));
        $provider = json_decode($jsonProvider, true);


        $filteredData = [];
        $dataPerProvider = [];

        foreach ($data as $item) {
            if (!isset($dataPerProvider[$item['provider']])) {
                $dataPerProvider[$item['provider']] = 0;
            }

            if ($dataPerProvider[$item['provider']] < 30) {
                $filteredData[] = $item;
                $dataPerProvider[$item['provider']]++;
            }
        }


        return view('rtpslot_page', ['data' => $filteredData,  'provider' => $provider]);
    }

    public function providerRtp($provider) {
        $jsonString = file_get_contents(database_path('json/data_rtp.json'));
        $data = json_decode($jsonString, true);

        $filterGames = array_filter($data, function($data) use ($provider){
            return $data['provider'] == $provider ;
        });

        return view('rtpslot_provider', ['games' => $filterGames,  "provider" => $provider ]);

    }

    public function edit()
    {
        $data = json_decode(File::get(database_path('json/data_rtp.json')), true);
        return view('edit', ['data' => $data]);
    }

    public function update(Request $request)
    {
        $data = json_decode(File::get(database_path('json/data_rtp.json')), true);

        foreach ($data as &$item) {

            $item['pola'] = $this->generateRandomString();
            $item['persentase'] = $this->generateRandomPercentage();
        }


        $result =File::put(database_path('json/data_rtp.json'), json_encode($data, JSON_PRETTY_PRINT));

        return response()->json(['success' => true, 'result' => $result]);
    }




    private function generateRandomString()
    {

        $variables = [
            '<span id="prov1-pola1">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola2">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Auto 50 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Auto 100 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1">Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1"> Auto 20 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3"> Auto 0 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 50 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3"> Auto 20 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span>',
            '<span id="prov1-pola1">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola2"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
            '<span id="prov1-pola1"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2"> Auto 70 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola2">Manual 3 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2"> Auto 30 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 9 <i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span><br><span id="prov1-pola3"> Auto 50 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i> </span>',
            '<span id="prov1-pola1"> Auto 10 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i> </span><br><span id="prov1-pola2">Manual 5 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i></span><br><span id="prov1-pola3">Manual 7 <i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-check fa-lg fa-fw text-success"></i><i class="fa-solid fa-xmark fa-lg fa-fw text-danger"></i></span>',
        ];


        $randomVariable = $variables[array_rand($variables)];

        return $randomVariable;

    }

    private function generateRandomPercentage() {
        $randomPercentage = rand(30, 100);
        return $randomPercentage;
    }

    public function updateUrl(Request $request)
    {
        $newUrl = $request->input('newUrl');

        $jsonString = file_get_contents(database_path('json/data_rtp.json'));
        $data = json_decode($jsonString, true);

        foreach ($data as &$item) {
            $item['url'] = preg_replace('/https:\/\/.*?\//', $newUrl . '/', $item['url']);
        }

        $result = File::put(database_path('json/data_rtp.json'), json_encode($data, JSON_PRETTY_PRINT));

        return response()->json(['success' => true, 'result' => $result]);
    }
}
